sonar.projectKey=valydar_sdk
sonar.projectName=valydar-sdk
sonar.sources=.
sonar.exclusions=worktree/**,**/node_modules/**,**/build/**,**/.gradle/**,**/__pycache__/**,**/dist/**,**/bin/**,**/obj/**,**/.dart_tool/**,**/Pods/**,**/.idea/**,**/target/**
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
